// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_def.go

package support // import "go.opentelemetry.io/ebpf-profiler/support"

const (
	FrameMarkerUnknown = 0x0
	FrameMarkerPython  = 0x1
	FrameMarkerNative  = 0x3
	FrameMarkerPHP     = 0x2
	FrameMarkerPHPJIT  = 0x9
	FrameMarkerKernel  = 0x4
	FrameMarkerHotSpot = 0x5
	FrameMarkerRuby    = 0x6
	FrameMarkerPerl    = 0x7
	FrameMarkerV8      = 0x8
	FrameMarkerDotnet  = 0xa
	FrameMarkerBEAM    = 0xc
	FrameMarkerGo      = 0xb
)

const (
	FrameFlagError         = 0x1
	FrameFlagReturnAddress = 0x2
	FrameFlagPidSpecific   = 0x4
)

const (
	ProgUnwindStop     = 0x0
	ProgUnwindNative   = 0x1
	ProgUnwindHotspot  = 0x2
	ProgUnwindPython   = 0x4
	ProgUnwindPHP      = 0x5
	ProgUnwindRuby     = 0x6
	ProgUnwindPerl     = 0x3
	ProgUnwindV8       = 0x7
	ProgUnwindDotnet   = 0x8
	ProgUnwindDotnet10 = 0x9
	ProgGoLabels       = 0xa
	ProgUnwindBEAM     = 0xb
)

const (
	DeltaCommandFlag = 0x8000

	MergeOpcodeNegative = 0x80
)

const (
	EventTypeGenericPID     = 0x1
	EventTypeReloadKallsyms = 0x2
)

const UnwindInfoMaxEntries = 0x4000

const (
	MetricIDBeginCumulative = 0x69
)

const (
	BitWidthPID  = 0x20
	BitWidthPage = 0x40
)

const (
	StackDeltaBucketSmallest = 0x8
	StackDeltaBucketLargest  = 0x17

	StackDeltaPageBits = 0x10
	StackDeltaPageMask = 0xffff
)

const (
	HSTSIDIsStubBit       = 0x3f
	HSTSIDHasFrameBit     = 0x3e
	HSTSIDStackDeltaBit   = 0x38
	HSTSIDStackDeltaMask  = 0x3f
	HSTSIDStackDeltaScale = 0x8
	HSTSIDSegMapBit       = 0x0
	HSTSIDSegMapMask      = 0xffffffffffffff
)

const (
	TraceOriginUnknown  = 0x0
	TraceOriginSampling = 0x1
	TraceOriginOffCPU   = 0x2
	TraceOriginProbe    = 0x3
)

type ApmSpanID [8]byte
type ApmTraceID [16]byte
type CustomLabel struct {
	Key [16]uint8
	Val [48]uint8
}
type CustomLabelsArray struct {
	Len    uint32
	Labels [10]CustomLabel
}
type Event struct {
	Type uint32
}
type OffsetRange struct {
	Lower_offset1 uint64
	Upper_offset1 uint64
	Lower_offset2 uint64
	Upper_offset2 uint64
	Program_index uint16
	Pad_cgo_0     [6]byte
}
type PIDPage struct {
	PrefixLen uint32
	Pid       uint32
	Page      uint64
}
type PIDPageMappingInfo struct {
	File_id                 uint64
	Bias_and_unwind_program uint64
}
type StackDelta struct {
	AddrLow    uint16
	UnwindInfo uint16
}
type StackDeltaPageInfo struct {
	FirstDelta uint32
	NumDeltas  uint16
	MapID      uint16
}
type StackDeltaPageKey struct {
	FileID uint64
	Page   uint64
}
type SystemAnalysis struct {
	Address   uint64
	Pid       uint32
	Code      [128]uint8
	Pad_cgo_0 [4]byte
}
type TSDInfo struct {
	Offset     int16
	Multiplier uint8
	Indirect   uint8
}
type DTVInfo struct {
	Offset     int16
	Multiplier uint8
	Pad_cgo_0  [1]byte
}
type Trace struct {
	Pid                uint32
	Tid                uint32
	Ktime              uint64
	Comm               [16]uint8
	Apm_transaction_id [8]byte
	Apm_trace_id       [16]byte
	Custom_labels      CustomLabelsArray
	Frame_data_len     uint16
	Num_frames         uint16
	Num_kernel_frames  uint16
	Origin             uint32
	Offtime            uint64
	Frame_data         [3072]uint64
}
type UnwindInfo struct {
	Flags       uint8
	BaseReg     uint8
	AuxBaseReg  uint8
	MergeOpcode uint8
	Param       int32
	AuxParam    int32
}

type ApmIntProcInfo struct {
	Offset uint64
}
type BEAMProcInfo struct {
	Bias                   uint64
	R                      uint64
	The_active_code_index  uint64
	Beam_normal_exit       uint64
	Frame_pointers_enabled bool
	Ranges_sizeof          uint8
	Pad_cgo_0              [6]byte
}
type DotnetProcInfo struct {
	Version uint32
}
type GoLabelsOffsets struct {
	M_offset               uint32
	Curg                   uint32
	Labels                 uint32
	Hmap_count             uint32
	Hmap_log2_bucket_count uint32
	Hmap_buckets           uint32
	Tls_offset             int32
}
type HotspotProcInfo struct {
	Codecache_start        uint64
	Codecache_end          uint64
	Nmethod_deopt_offset   uint16
	Nmethod_compileid      uint16
	Nmethod_orig_pc_offset uint16
	Codeblob_name          uint8
	Codeblob_codestart     uint8
	Codeblob_codeend       uint8
	Codeblob_framecomplete uint8
	Codeblob_framesize     uint8
	Heapblock_size         uint8
	Method_constmethod     uint8
	Cmethod_size           uint8
	Jvm_version            uint8
	New_bcp_slot           uint8
	Segment_shift          uint8
	Nmethod_uses_offsets   uint8
	Pad_cgo_0              [6]byte
}
type PHPProcInfo struct {
	Current_execute_data                uint64
	Jit_return_address                  uint64
	Zend_execute_data_function          uint8
	Zend_execute_data_opline            uint8
	Zend_execute_data_prev_execute_data uint8
	Zend_execute_data_this_type_info    uint8
	Zend_function_type                  uint8
	Zend_op_lineno                      uint8
	Pad_cgo_0                           [2]byte
}
type PerlProcInfo struct {
	StateAddr                uint64
	Version                  uint32
	TsdInfo                  TSDInfo
	Interpreter_curcop       uint16
	Interpreter_curstackinfo uint16
	StateInTSD               uint8
	Si_cxstack               uint8
	Si_next                  uint8
	Si_cxix                  uint8
	Si_type                  uint8
	Context_type             uint8
	Context_blk_oldcop       uint8
	Context_blk_sub_retop    uint8
	Context_blk_sub_cv       uint8
	Context_sizeof           uint8
	Sv_flags                 uint8
	Sv_any                   uint8
	Svu_gp                   uint8
	Xcv_flags                uint8
	Xcv_gv                   uint8
	Gp_egv                   uint8
	Pad_cgo_0                [4]byte
}
type PyProcInfo struct {
	AutoTLSKeyAddr                 uint64
	NoneStructAddr                 uint64
	Version                        uint16
	Tls_offset                     int16
	TsdInfo                        TSDInfo
	PyThreadState_frame            uint8
	PyCFrame_current_frame         uint8
	PyFrameObject_f_back           uint8
	PyFrameObject_f_code           uint8
	PyFrameObject_f_lasti          uint8
	PyFrameObject_entry_member     uint8
	PyFrameObject_entry_val        uint8
	PyCodeObject_co_argcount       uint8
	PyCodeObject_co_kwonlyargcount uint8
	PyCodeObject_co_flags          uint8
	PyCodeObject_co_firstlineno    uint8
	PyCodeObject_sizeof            uint8
	Lasti_is_codeunit              uint8
	Frame_is_cframe                uint8
	Pad_cgo_0                      [2]byte
}
type RubyProcInfo struct {
	Version                      uint32
	Current_ec_tpbase_tls_offset int64
	Dtv_info                     DTVInfo
	Current_ec_tls_offset        uint64
	Tls_module_id                uint32
	Current_ctx_ptr              uint64
	Has_objspace                 bool
	Vm_stack                     uint8
	Vm_stack_size                uint8
	Cfp                          uint8
	Thread_ptr                   uint8
	Thread_vm                    uint8
	Vm_objspace                  uint16
	Objspace_flags               uint8
	Objspace_size_of_flags       uint8
	Pc                           uint8
	Iseq                         uint8
	Ep                           uint8
	Size_of_control_frame_struct uint8
	Body                         uint8
	Cme_method_def               uint8
	Size_of_value                uint8
	Running_ec                   uint16
	Pad_cgo_0                    [4]byte
}
type V8ProcInfo struct {
	Version                      uint32
	Type_JSFunction_first        uint16
	Type_JSFunction_last         uint16
	Type_Code                    uint16
	Type_SharedFunctionInfo      uint16
	Off_HeapObject_map           uint8
	Off_Map_instancetype         uint8
	Off_JSFunction_code          uint8
	Off_JSFunction_shared        uint8
	Code_instructions_is_pointer uint8
	Off_Code_instruction_start   uint8
	Off_Code_instruction_size    uint8
	Off_Code_flags               uint8
	Fp_marker                    uint8
	Fp_function                  uint8
	Fp_bytecode_offset           uint8
	Codekind_shift               uint8
	Codekind_mask                uint8
	Codekind_baseline            uint8
	Pad_cgo_0                    [2]byte
}

const (
	Sizeof_StackDelta = 0x4
	Sizeof_Trace      = 0x62d0

	sizeof_ApmIntProcInfo = 0x8
	sizeof_DotnetProcInfo = 0x4
	sizeof_PHPProcInfo    = 0x18
	sizeof_RubyProcInfo   = 0x48
)

const (
	UnwindRegInvalid uint8 = 0x0
	UnwindRegCfa     uint8 = 0x1
	UnwindRegPc      uint8 = 0x2
	UnwindRegSp      uint8 = 0x3
	UnwindRegFp      uint8 = 0x4
	UnwindRegLr      uint8 = 0x5
	UnwindRegX86RAX  uint8 = 0x6
	UnwindRegX86R9   uint8 = 0x7
	UnwindRegX86R11  uint8 = 0x8
	UnwindRegX86R15  uint8 = 0xa

	UnwindFlagCommand  uint8 = 0x1
	UnwindFlagFrame    uint8 = 0x2
	UnwindFlagLeafOnly uint8 = 0x4
	UnwindFlagDerefCfa uint8 = 0x8

	UnwindCommandInvalid      int32 = 0x0
	UnwindCommandStop         int32 = 0x1
	UnwindCommandPLT          int32 = 0x2
	UnwindCommandSignal       int32 = 0x3
	UnwindCommandFramePointer int32 = 0x4

	UnwindDerefMask       int32 = 0x7
	UnwindDerefMultiplier int32 = 0x8
)

const (
	FrameHotspotStub        = 0x0
	FrameHotspotVtable      = 0x1
	FrameHotspotInterpreter = 0x2
	FrameHotspotNative      = 0x3

	V8SmiTag            = 0x0
	V8SmiTagMask        = 0x1
	V8SmiTagShift       = 0x1
	V8SmiValueShift     = 0x20
	V8HeapObjectTag     = 0x1
	V8HeapObjectTagMask = 0x3

	V8FpContextSize = 0x40

	V8FileTypeMarker       = 0x0
	V8FileTypeByteCode     = 0x1
	V8FileTypeNativeSFI    = 0x2
	V8FileTypeNativeCode   = 0x3
	V8FileTypeNativeJSFunc = 0x4
	V8FileTypeMask         = 0x7

	V8LineCookieShift = 0x20
	V8LineCookieMask  = 0xffffffff00000000
	V8LineDeltaMask   = 0xffffffff

	RubyFrameTypeNone     = 0x0
	RubyFrameTypeCmeIseq  = 0x1
	RubyFrameTypeCmeCfunc = 0x2
	RubyFrameTypeIseq     = 0x3
	RubyFrameTypeGc       = 0x4
)
