// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("go.opentelemetry.io/ebpf-profiler/collector")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("go.opentelemetry.io/ebpf-profiler/collector")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                      metric.Meter
	mu                                         sync.Mutex
	registrations                              []metric.Registration
	AgentDotnetAddrToMethodHits                metric.Int64Counter
	AgentDotnetAddrToMethodMisses              metric.Int64Counter
	AgentDotnetSymbolizationFailures           metric.Int64Counter
	AgentDotnetSymbolizationSuccesses          metric.Int64Counter
	AgentElfInfoCacheHits                      metric.Int64Counter
	AgentElfInfoCacheMisses                    metric.Int64Counter
	AgentErrorsExeIDToStackDeltasBatchUpdate   metric.Int64Counter
	AgentErrorsExeIDToStackDeltasUpdate        metric.Int64Counter
	AgentErrorsPerfEventLost                   metric.Int64Counter
	AgentErrorsPerfEventNoData                 metric.Int64Counter
	AgentErrorsPerfEventReadError              metric.Int64Counter
	AgentErrorsPidPageToMappingInfoBatchDelete metric.Int64Counter
	AgentErrorsPidPageToMappingInfoDelete      metric.Int64Counter
	AgentErrorsPidPageToMappingInfoUpdate      metric.Int64Counter
	AgentErrorsProcEsrch                       metric.Int64Counter
	AgentErrorsProcNotExists                   metric.Int64Counter
	AgentErrorsProcParse                       metric.Int64Counter
	AgentErrorsProcPerm                        metric.Int64Counter
	AgentErrorsStackDeltaPageToInfoBatchUpdate metric.Int64Counter
	AgentErrorsStackDeltaPageToInfoDelete      metric.Int64Counter
	AgentErrorsStackDeltaPageToInfoUpdate      metric.Int64Counter
	AgentErrorsStackDeltaProviderExtraction    metric.Int64Counter
	AgentErrorsTraceEventLost                  metric.Int64Counter
	AgentErrorsTraceEventNoData                metric.Int64Counter
	AgentErrorsTraceEventReadError             metric.Int64Counter
	AgentErrorsUnwindInfoArrayUpdate           metric.Int64Counter
	AgentGoSymbolizationFailures               metric.Int64Counter
	AgentGoSymbolizationSuccesses              metric.Int64Counter
	AgentHashmapPidPageToMappingInfoSize       metric.Int64Gauge
	AgentHotspotAddrToJitInfoAdd               metric.Int64Counter
	AgentHotspotAddrToJitInfoDel               metric.Int64Counter
	AgentHotspotAddrToJitInfoHits              metric.Int64Counter
	AgentHotspotAddrToJitInfoMisses            metric.Int64Counter
	AgentHotspotAddrToMethodAdd                metric.Int64Counter
	AgentHotspotAddrToMethodDel                metric.Int64Counter
	AgentHotspotAddrToMethodHits               metric.Int64Counter
	AgentHotspotAddrToMethodMisses             metric.Int64Counter
	AgentHotspotAddrToStubNameAdd              metric.Int64Counter
	AgentHotspotAddrToStubNameDel              metric.Int64Counter
	AgentHotspotAddrToStubNameIDHits           metric.Int64Counter
	AgentHotspotAddrToStubNameIDMisses         metric.Int64Counter
	AgentHotspotAddrToSymbolAdd                metric.Int64Counter
	AgentHotspotAddrToSymbolDel                metric.Int64Counter
	AgentHotspotAddrToSymbolHits               metric.Int64Counter
	AgentHotspotAddrToSymbolMisses             metric.Int64Counter
	AgentHotspotSymbolizationFailures          metric.Int64Counter
	AgentHotspotSymbolizationSuccesses         metric.Int64Counter
	AgentKernelFallbackSymbolLruHits           metric.Int64Counter
	AgentKernelFallbackSymbolLruMisses         metric.Int64Counter
	AgentMaxProcParseUs                        metric.Int64Gauge
	AgentNumExeIDLoadedToEbpf                  metric.Int64Gauge
	AgentNumGenericPid                         metric.Int64Counter
	AgentNumProcAttempts                       metric.Int64Counter
	AgentPerlAddrToCopAdd                      metric.Int64Counter
	AgentPerlAddrToCopDel                      metric.Int64Counter
	AgentPerlAddrToCopHits                     metric.Int64Counter
	AgentPerlAddrToCopMisses                   metric.Int64Counter
	AgentPerlAddrToGvAdd                       metric.Int64Counter
	AgentPerlAddrToGvDel                       metric.Int64Counter
	AgentPerlAddrToGvHits                      metric.Int64Counter
	AgentPerlAddrToGvMisses                    metric.Int64Counter
	AgentPerlAddrToHekAdd                      metric.Int64Counter
	AgentPerlAddrToHekDel                      metric.Int64Counter
	AgentPerlAddrToHekHits                     metric.Int64Counter
	AgentPerlAddrToHekMisses                   metric.Int64Counter
	AgentPerlHekLen                            metric.Int64Gauge
	AgentPerlSymbolizationFailures             metric.Int64Counter
	AgentPerlSymbolizationSuccesses            metric.Int64Counter
	AgentPhpAddrToFuncAdd                      metric.Int64Counter
	AgentPhpAddrToFuncDel                      metric.Int64Counter
	AgentPhpAddrToFuncHits                     metric.Int64Counter
	AgentPhpAddrToFuncMisses                   metric.Int64Counter
	AgentPhpErrorsFailedToFindReturnAddress    metric.Int64Counter
	AgentPhpSymbolizationFailures              metric.Int64Counter
	AgentPhpSymbolizationSuccesses             metric.Int64Counter
	AgentPythonAddrToCodeObjectAdd             metric.Int64Counter
	AgentPythonAddrToCodeObjectDel             metric.Int64Counter
	AgentPythonAddrToCodeObjectHits            metric.Int64Counter
	AgentPythonAddrToCodeObjectMisses          metric.Int64Counter
	AgentPythonSymbolizationFailures           metric.Int64Counter
	AgentPythonSymbolizationSuccesses          metric.Int64Counter
	AgentRubyAddrToStringAdd                   metric.Int64Counter
	AgentRubyAddrToStringDel                   metric.Int64Counter
	AgentRubyAddrToStringHits                  metric.Int64Counter
	AgentRubyAddrToStringMisses                metric.Int64Counter
	AgentRubyMaxSize                           metric.Int64Gauge
	AgentRubySymbolizationFailures             metric.Int64Counter
	AgentRubySymbolizationSuccesses            metric.Int64Counter
	AgentStackDeltaExtractionSuccess           metric.Int64Counter
	AgentStackDeltaPagesSize                   metric.Int64Gauge
	AgentTimeProcPidStartup                    metric.Int64Counter
	AgentTimeTotalProcParse                    metric.Int64Counter
	AgentTraceCacheHits                        metric.Int64Counter
	AgentTraceCacheMisses                      metric.Int64Counter
	AgentUnwindInfoArraySize                   metric.Int64Gauge
	AgentV8AddrToFuncAdd                       metric.Int64Counter
	AgentV8AddrToFuncDel                       metric.Int64Counter
	AgentV8AddrToFuncHits                      metric.Int64Counter
	AgentV8AddrToFuncMisses                    metric.Int64Counter
	AgentV8AddrToSfiAdd                        metric.Int64Counter
	AgentV8AddrToSfiDel                        metric.Int64Counter
	AgentV8AddrToSfiHits                       metric.Int64Counter
	AgentV8AddrToSfiMisses                     metric.Int64Counter
	AgentV8AddrToSourceAdd                     metric.Int64Counter
	AgentV8AddrToSourceDel                     metric.Int64Counter
	AgentV8AddrToSourceHits                    metric.Int64Counter
	AgentV8AddrToSourceMisses                  metric.Int64Counter
	AgentV8AddrToStringAdd                     metric.Int64Counter
	AgentV8AddrToStringDel                     metric.Int64Counter
	AgentV8AddrToStringHits                    metric.Int64Counter
	AgentV8AddrToStringMisses                  metric.Int64Counter
	AgentV8SymbolizationFailures               metric.Int64Counter
	AgentV8SymbolizationSuccesses              metric.Int64Counter
	BpfApmintErrorsReadCorrBuf                 metric.Int64Counter
	BpfApmintErrorsReadCorrBufPtr              metric.Int64Counter
	BpfApmintErrorsReadTsdBase                 metric.Int64Counter
	BpfApmintReadSuccesses                     metric.Int64Counter
	BpfDotnetAttempts                          metric.Int64Counter
	BpfDotnetErrorsBadFp                       metric.Int64Counter
	BpfDotnetErrorsCodeHeader                  metric.Int64Counter
	BpfDotnetErrorsCodeTooLarge                metric.Int64Counter
	BpfDotnetErrorsNoProcInfo                  metric.Int64Counter
	BpfDotnetFrames                            metric.Int64Counter
	BpfErrorsBadDtvRead                        metric.Int64Counter
	BpfErrorsBadTLSAddr                        metric.Int64Counter
	BpfErrorsBadTpBaseAddr                     metric.Int64Counter
	BpfErrorsBpfCurrentComm                    metric.Int64Counter
	BpfErrorsEmptyStack                        metric.Int64Counter
	BpfErrorsPidEvents                         metric.Int64Counter
	BpfErrorsReportedPids                      metric.Int64Counter
	BpfErrorsStackLengthExceeded               metric.Int64Counter
	BpfErrorsZeroPc                            metric.Int64Counter
	BpfGolabelsAttempts                        metric.Int64Counter
	BpfGolabelsErrors                          metric.Int64Counter
	BpfHotspotAttempts                         metric.Int64Counter
	BpfHotspotErrorsInterpreterFp              metric.Int64Counter
	BpfHotspotErrorsInvalidCodeblob            metric.Int64Counter
	BpfHotspotErrorsInvalidRa                  metric.Int64Counter
	BpfHotspotErrorsLrUnwindingMidTrace        metric.Int64Counter
	BpfHotspotErrorsNoCodeblob                 metric.Int64Counter
	BpfHotspotErrorsUnsupportedFrameSize       metric.Int64Counter
	BpfHotspotFrames                           metric.Int64Counter
	BpfInterpreterCalls                        metric.Int64Counter
	BpfNativeAttempts                          metric.Int64Counter
	BpfNativeErrorsBadUnwindInfoIndex          metric.Int64Counter
	BpfNativeErrorsChaseIrqStackLink           metric.Int64Counter
	BpfNativeErrorsKernelAddress               metric.Int64Counter
	BpfNativeErrorsLookupIterations            metric.Int64Counter
	BpfNativeErrorsLookupRange                 metric.Int64Counter
	BpfNativeErrorsLookupStackDeltaInnerMap    metric.Int64Counter
	BpfNativeErrorsLookupStackDeltaOuterMap    metric.Int64Counter
	BpfNativeErrorsLookupTextSection           metric.Int64Counter
	BpfNativeErrorsLr0                         metric.Int64Counter
	BpfNativeErrorsLrUnwindingMidTrace         metric.Int64Counter
	BpfNativeErrorsPcRead                      metric.Int64Counter
	BpfNativeErrorsReadKernelModeRegs          metric.Int64Counter
	BpfNativeErrorsStackDeltaInvalid           metric.Int64Counter
	BpfNativeErrorsWrongTextSection            metric.Int64Counter
	BpfNativeFrames                            metric.Int64Counter
	BpfNativeSmallPc                           metric.Int64Counter
	BpfNativeStackDeltaStop                    metric.Int64Counter
	BpfNumProcExit                             metric.Int64Counter
	BpfNumProcNew                              metric.Int64Counter
	BpfNumUnknownPc                            metric.Int64Counter
	BpfPerlAttempts                            metric.Int64Counter
	BpfPerlErrorsReadContextStackEntry         metric.Int64Counter
	BpfPerlErrorsReadStackInfo                 metric.Int64Counter
	BpfPerlErrorsResolveEgv                    metric.Int64Counter
	BpfPerlErrorsTLS                           metric.Int64Counter
	BpfPerlFrames                              metric.Int64Counter
	BpfPhpAttempts                             metric.Int64Counter
	BpfPhpErrorsBadCurrentExecuteData          metric.Int64Counter
	BpfPhpErrorsBadZendExecuteData             metric.Int64Counter
	BpfPhpErrorsBadZendFunction                metric.Int64Counter
	BpfPhpErrorsBadZendOpline                  metric.Int64Counter
	BpfPhpFrames                               metric.Int64Counter
	BpfPythonAttempts                          metric.Int64Counter
	BpfPythonErrorsBadAutoTLSKeyAddr           metric.Int64Counter
	BpfPythonErrorsBadCframeFrameAddr          metric.Int64Counter
	BpfPythonErrorsBadCodeObjectArgCountAddr   metric.Int64Counter
	BpfPythonErrorsBadPyThreadStateCurrentAddr metric.Int64Counter
	BpfPythonErrorsBadThreadStateFrameAddr     metric.Int64Counter
	BpfPythonErrorsNoProcInfo                  metric.Int64Counter
	BpfPythonErrorsReadThreadStateAddr         metric.Int64Counter
	BpfPythonErrorsReadTsdBase                 metric.Int64Counter
	BpfPythonErrorsZeroThreadState             metric.Int64Counter
	BpfPythonFrames                            metric.Int64Counter
	BpfPythonZeroFrameCodeObject               metric.Int64Counter
	BpfRubyAttempts                            metric.Int64Counter
	BpfRubyErrorsInvalidIseq                   metric.Int64Counter
	BpfRubyErrorsNoProcInfo                    metric.Int64Counter
	BpfRubyErrorsReadCfp                       metric.Int64Counter
	BpfRubyErrorsReadCmeMaxEp                  metric.Int64Counter
	BpfRubyErrorsReadEp                        metric.Int64Counter
	BpfRubyErrorsReadIseqBody                  metric.Int64Counter
	BpfRubyErrorsReadMethodDef                 metric.Int64Counter
	BpfRubyErrorsReadMethodType                metric.Int64Counter
	BpfRubyErrorsReadRbasicFlags               metric.Int64Counter
	BpfRubyErrorsReadStackPtr                  metric.Int64Counter
	BpfRubyErrorsReadStackSize                 metric.Int64Counter
	BpfRubyErrorsReadSvar                      metric.Int64Counter
	BpfRubyFrames                              metric.Int64Counter
	BpfTailCallsMax                            metric.Int64Counter
	BpfV8Attempts                              metric.Int64Counter
	BpfV8ErrorsBadCode                         metric.Int64Counter
	BpfV8ErrorsBadFp                           metric.Int64Counter
	BpfV8ErrorsBadJsFunc                       metric.Int64Counter
	BpfV8ErrorsNoProcInfo                      metric.Int64Counter
	BpfV8Frames                                metric.Int64Counter
	PerfEventDisableErr                        metric.Int64Counter
	PerfEventEnableErr                         metric.Int64Counter
	ProbProfilingInterval                      metric.Int64Gauge
	ProbProfilingStatus                        metric.Int64Gauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.AgentDotnetAddrToMethodHits, err = builder.meter.Int64Counter(
		"otelcol_agent.dotnet.addr_to_method.hits",
		metric.WithDescription("Number of cache hits for dotnet AddrToMethod [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentDotnetAddrToMethodMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.dotnet.addr_to_method.misses",
		metric.WithDescription("Number of cache misses for dotnet AddrToMethod [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentDotnetSymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.dotnet.symbolization.failures",
		metric.WithDescription("Number of dotnet frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentDotnetSymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.dotnet.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized dotnet frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentElfInfoCacheHits, err = builder.meter.Int64Counter(
		"otelcol_agent.elf_info_cache.hits",
		metric.WithDescription("Number of cache hits for ELF information [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentElfInfoCacheMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.elf_info_cache.misses",
		metric.WithDescription("Number of cache misses for ELF information [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsExeIDToStackDeltasBatchUpdate, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.exe_id_to_stack_deltas_batch_update",
		metric.WithDescription("Number of times batch updating elements in exeIDToStackDeltas failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsExeIDToStackDeltasUpdate, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.exe_id_to_stack_deltas_update",
		metric.WithDescription("Number of times updating an element in exeIDToStackDeltas failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsPerfEventLost, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.perf_event_lost",
		metric.WithDescription("Number of lost perf events in the communication between kernel and user space (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsPerfEventNoData, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.perf_event_no_data",
		metric.WithDescription("Number of times a perf event was received without data (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsPerfEventReadError, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.perf_event_read_error",
		metric.WithDescription("Number of times a perf event read failed (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsPidPageToMappingInfoBatchDelete, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.pid_page_to_mapping_info_batch_delete",
		metric.WithDescription("Number of times batch deleting elements from pidPageToMappingInfo failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsPidPageToMappingInfoDelete, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.pid_page_to_mapping_info_delete",
		metric.WithDescription("Number of times deleting an element from pidPageToMappingInfo failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsPidPageToMappingInfoUpdate, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.pid_page_to_mapping_info_update",
		metric.WithDescription("Number of times updating an element in pidPageToMappingInfo failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsProcEsrch, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.proc_esrch",
		metric.WithDescription("Number of times process exits while reading /proc/<PID> [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsProcNotExists, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.proc_not_exists",
		metric.WithDescription("Number of times reading /proc/<PID> as it does not exist anymore [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsProcParse, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.proc_parse",
		metric.WithDescription("Number of parsing errors seen during processing /proc/<PID>/maps [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsProcPerm, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.proc_perm",
		metric.WithDescription("Number of times reading /proc/<PID> failed due to missing permission [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsStackDeltaPageToInfoBatchUpdate, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.stack_delta_page_to_info_batch_update",
		metric.WithDescription("Number of times batch updating elements in stackDeltaPageToInfo failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsStackDeltaPageToInfoDelete, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.stack_delta_page_to_info_delete",
		metric.WithDescription("Number of times deleting an element from stackDeltaPageToInfo failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsStackDeltaPageToInfoUpdate, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.stack_delta_page_to_info_update",
		metric.WithDescription("Number of times updating an element in stackDeltaPageToInfo failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsStackDeltaProviderExtraction, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.stack_delta_provider_extraction",
		metric.WithDescription("Number of times the stack delta provider failed to extract stack deltas [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsTraceEventLost, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.trace_event_lost",
		metric.WithDescription("Number of lost trace events in the communication between kernel and user space (trace_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsTraceEventNoData, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.trace_event_no_data",
		metric.WithDescription("Number of times a trace event was received without data (trace_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsTraceEventReadError, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.trace_event_read_error",
		metric.WithDescription("Number of times a trace event read failed (trace_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentErrorsUnwindInfoArrayUpdate, err = builder.meter.Int64Counter(
		"otelcol_agent.errors.unwind_info_array_update",
		metric.WithDescription("Number of times updating an element in unwindInfoArray failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentGoSymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.go.symbolization.failures",
		metric.WithDescription("Number of Go frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentGoSymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.go.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized Go frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHashmapPidPageToMappingInfoSize, err = builder.meter.Int64Gauge(
		"otelcol_agent.hashmap_pid_page_to_mapping_info.size",
		metric.WithDescription("Current size of the hash map pid_page_to_mapping_info [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToJitInfoAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_jit_info.add",
		metric.WithDescription("Number of added cache elements for Hotspot AddrToJITInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToJitInfoDel, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_jit_info.del",
		metric.WithDescription("Number of deleted cache elements for Hotspot AddrToJITInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToJitInfoHits, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_jit_info.hits",
		metric.WithDescription("Number of cache hits for Hotspot AddrToJITInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToJitInfoMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_jit_info.misses",
		metric.WithDescription("Number of cache misses for Hotspot AddrToJITInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToMethodAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_method.add",
		metric.WithDescription("Number of added cache elements for Hotspot AddrToMethod [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToMethodDel, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_method.del",
		metric.WithDescription("Number of deleted cache elements for Hotspot AddrToMethod [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToMethodHits, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_method.hits",
		metric.WithDescription("Number of cache hits for Hotspot AddrToMethod [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToMethodMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_method.misses",
		metric.WithDescription("Number of cache misses for Hotspot AddrToMethod [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToStubNameAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_stub_name.add",
		metric.WithDescription("Number of added cache elements for Hotspot AddrToStubNameID [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToStubNameDel, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_stub_name.del",
		metric.WithDescription("Number of deleted cache elements for Hotspot AddrToStubNameID [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToStubNameIDHits, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_stub_name_id.hits",
		metric.WithDescription("Number of cache hits for Hotspot AddrToStubNameID [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToStubNameIDMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_stub_name_id.misses",
		metric.WithDescription("Number of cache misses for Hotspot AddrToStubNameID [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToSymbolAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_symbol.add",
		metric.WithDescription("Number of added cache elements for Hotspot AddrToSymbol [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToSymbolDel, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_symbol.del",
		metric.WithDescription("Number of deleted cache elements for Hotspot AddrToSymbol [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToSymbolHits, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_symbol.hits",
		metric.WithDescription("Number of cache hits for Hotspot AddrToSymbol [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotAddrToSymbolMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.addr_to_symbol.misses",
		metric.WithDescription("Number of cache misses for Hotspot AddrToSymbol [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotSymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.symbolization.failures",
		metric.WithDescription("Number of Hotspot frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentHotspotSymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.hotspot.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized hotspot frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentKernelFallbackSymbolLruHits, err = builder.meter.Int64Counter(
		"otelcol_agent.kernel.fallback_symbol_lru.hits",
		metric.WithDescription("Number of LRU hits for kernel symbols [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentKernelFallbackSymbolLruMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.kernel.fallback_symbol_lru.misses",
		metric.WithDescription("Number of LRU mises for kernel symbols [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentMaxProcParseUs, err = builder.meter.Int64Gauge(
		"otelcol_agent.max_proc_parse.us",
		metric.WithDescription("Max /proc/PID/maps parse time for a single collection interval. [Development]"),
		metric.WithUnit("us"),
	)
	errs = errors.Join(errs, err)
	builder.AgentNumExeIDLoadedToEbpf, err = builder.meter.Int64Gauge(
		"otelcol_agent.num_exe_id_loaded_to_ebpf",
		metric.WithDescription("The number of executables loaded to eBPF maps [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentNumGenericPid, err = builder.meter.Int64Counter(
		"otelcol_agent.num_generic_pid",
		metric.WithDescription("Number of generic PID events (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentNumProcAttempts, err = builder.meter.Int64Counter(
		"otelcol_agent.num_proc_attempts",
		metric.WithDescription("Number of /proc/PID/maps process attempts [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToCopAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_cop.add",
		metric.WithDescription("Number of added cache elements for Perl AddrToCOP [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToCopDel, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_cop.del",
		metric.WithDescription("Number of deleted cache elements for Perl AddrToCOP [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToCopHits, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_cop.hits",
		metric.WithDescription("Number of cache hits for Perl AddrToCOP [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToCopMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_cop.misses",
		metric.WithDescription("Number of cache misses for Perl AddrToCOP [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToGvAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_gv.add",
		metric.WithDescription("Number of added cache elements for Perl AddrToGV [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToGvDel, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_gv.del",
		metric.WithDescription("Number of deleted cache elementes Perl AddrToGV [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToGvHits, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_gv.hits",
		metric.WithDescription("Number of cache hits for Perl AddrToGV [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToGvMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_gv.misses",
		metric.WithDescription("Number of cache misses for Perl AddrToGV [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToHekAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_hek.add",
		metric.WithDescription("Number of added cache elements for Perl AddrToHEK [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToHekDel, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_hek.del",
		metric.WithDescription("Number of deleted cache elements for Perl AddrToHEK [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToHekHits, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_hek.hits",
		metric.WithDescription("Number of cache hits for Perl AddrToHEK [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlAddrToHekMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.addr_to_hek.misses",
		metric.WithDescription("Number of cache misses for Perl AddrToHEK [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlHekLen, err = builder.meter.Int64Gauge(
		"otelcol_agent.perl.hek_len",
		metric.WithDescription("Maximum number of hekLen that was requested within the last reporting interval. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlSymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.symbolization.failures",
		metric.WithDescription("Number of Perl frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPerlSymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.perl.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized Perl frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpAddrToFuncAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.php.addr_to_func.add",
		metric.WithDescription("Number of added cache elements for PHP AddrToFunc [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpAddrToFuncDel, err = builder.meter.Int64Counter(
		"otelcol_agent.php.addr_to_func.del",
		metric.WithDescription("Number of deleted cache elements for PHP AddrToFunc [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpAddrToFuncHits, err = builder.meter.Int64Counter(
		"otelcol_agent.php.addr_to_func.hits",
		metric.WithDescription("Number of cache hits for PHP AddrToFunc [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpAddrToFuncMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.php.addr_to_func.misses",
		metric.WithDescription("Number of cache misses for PHP AddrToFunc [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpErrorsFailedToFindReturnAddress, err = builder.meter.Int64Counter(
		"otelcol_agent.php.errors.failed_to_find_return_address",
		metric.WithDescription("Number of times finding the return address in the interpreter loop failed for PHP 8+. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpSymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.php.symbolization.failures",
		metric.WithDescription("Number of PHP frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPhpSymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.php.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized PHP frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPythonAddrToCodeObjectAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.python.addr_to_code_object.add",
		metric.WithDescription("Number of added cache elements for Python AddrToCodeObject [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPythonAddrToCodeObjectDel, err = builder.meter.Int64Counter(
		"otelcol_agent.python.addr_to_code_object.del",
		metric.WithDescription("Number of deleted cache elements for Python AddrToCodeObject [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPythonAddrToCodeObjectHits, err = builder.meter.Int64Counter(
		"otelcol_agent.python.addr_to_code_object.hits",
		metric.WithDescription("Number of cache hits for Python AddrToCodeObject [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPythonAddrToCodeObjectMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.python.addr_to_code_object.misses",
		metric.WithDescription("Number of cache misses for Python AddrToCodeObject [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPythonSymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.python.symbolization.failures",
		metric.WithDescription("Number of Python frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentPythonSymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.python.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized python frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubyAddrToStringAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.ruby.addr_to_string.add",
		metric.WithDescription("Number of added cache elements for Ruby AddrToString [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubyAddrToStringDel, err = builder.meter.Int64Counter(
		"otelcol_agent.ruby.addr_to_string.del",
		metric.WithDescription("Number of deleted cache elements for Ruby AddrToString [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubyAddrToStringHits, err = builder.meter.Int64Counter(
		"otelcol_agent.ruby.addr_to_string.hits",
		metric.WithDescription("Number of cache hits for Ruby AddrToString [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubyAddrToStringMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.ruby.addr_to_string.misses",
		metric.WithDescription("Number of cache misses for Ruby AddrToString [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubyMaxSize, err = builder.meter.Int64Gauge(
		"otelcol_agent.ruby.max_size",
		metric.WithDescription("Maximum number of size that was requested within the last reporting interval. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubySymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.ruby.symbolization.failures",
		metric.WithDescription("Number of Ruby frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentRubySymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.ruby.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized Ruby frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentStackDeltaExtractionSuccess, err = builder.meter.Int64Counter(
		"otelcol_agent.stack_delta_extraction.success",
		metric.WithDescription("Number of times the stack delta provider succeeded to extract stack deltas [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentStackDeltaPagesSize, err = builder.meter.Int64Gauge(
		"otelcol_agent.stack_delta_pages.size",
		metric.WithDescription("Current size of the stack delta pages hash map [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentTimeProcPidStartup, err = builder.meter.Int64Counter(
		"otelcol_agent.time.proc_pid_startup",
		metric.WithDescription("Time spent processing /proc/PID/maps on startup, in milliseconds [Development]"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	builder.AgentTimeTotalProcParse, err = builder.meter.Int64Counter(
		"otelcol_agent.time.total_proc_parse",
		metric.WithDescription("Total /proc/PID/maps parse time for a single collection interval. [Development]"),
		metric.WithUnit("us"),
	)
	errs = errors.Join(errs, err)
	builder.AgentTraceCacheHits, err = builder.meter.Int64Counter(
		"otelcol_agent.trace_cache.hits",
		metric.WithDescription("Number of cache hits in tracehandler trace cache by UM hash [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentTraceCacheMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.trace_cache.misses",
		metric.WithDescription("Number of cache misses in tracehandler trace cache by UM hash [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentUnwindInfoArraySize, err = builder.meter.Int64Gauge(
		"otelcol_agent.unwind_info_array.size",
		metric.WithDescription("Current size of the unwind info array [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToFuncAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_func.add",
		metric.WithDescription("Number of added cache elements for V8 Code/JSFunction [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToFuncDel, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_func.del",
		metric.WithDescription("Number of deleted cache elements for V8 Code/JSFunction [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToFuncHits, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_func.hits",
		metric.WithDescription("Number of cache hits for V8 Code/JSFunction [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToFuncMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_func.misses",
		metric.WithDescription("Number of cache misses for V8 Code/JSFunction [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSfiAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_sfi.add",
		metric.WithDescription("Number of added cache elements for V8 SharedFunctionInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSfiDel, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_sfi.del",
		metric.WithDescription("Number of deleted cache elements for V8 SharedFunctionInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSfiHits, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_sfi.hits",
		metric.WithDescription("Number of cache hits for V8 SharedFunctionInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSfiMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_sfi.misses",
		metric.WithDescription("Number of cache misses for V8 SharedFunctionInfo [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSourceAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_source.add",
		metric.WithDescription("Number of added cache elements for V8 Source [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSourceDel, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_source.del",
		metric.WithDescription("Number of deleted cache elements for V8 Source [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSourceHits, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_source.hits",
		metric.WithDescription("Number of cache hits for V8 Source [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToSourceMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_source.misses",
		metric.WithDescription("Number of cache misses for V8 Source [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToStringAdd, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_string.add",
		metric.WithDescription("Number of added cache elements for V8 strings [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToStringDel, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_string.del",
		metric.WithDescription("Number of deleted cache elements for V8 strings [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToStringHits, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_string.hits",
		metric.WithDescription("Number of cache hits for V8 strings [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8AddrToStringMisses, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.addr_to_string.misses",
		metric.WithDescription("Number of cache misses for V8 strings [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8SymbolizationFailures, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.symbolization.failures",
		metric.WithDescription("Number of V8 frames that failed symbolization [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.AgentV8SymbolizationSuccesses, err = builder.meter.Int64Counter(
		"otelcol_agent.v8.symbolization.successes",
		metric.WithDescription("Number of successfully symbolized V8 frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfApmintErrorsReadCorrBuf, err = builder.meter.Int64Counter(
		"otelcol_bpf.apmint.errors.read_corr_buf",
		metric.WithDescription("Number of failures read the APM correlation buffer [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfApmintErrorsReadCorrBufPtr, err = builder.meter.Int64Counter(
		"otelcol_bpf.apmint.errors.read_corr_buf_ptr",
		metric.WithDescription("Number of failures read the APM correlation pointer [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfApmintErrorsReadTsdBase, err = builder.meter.Int64Counter(
		"otelcol_bpf.apmint.errors.read_tsd_base",
		metric.WithDescription("Number of failures to get TSD base for APM correlation [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfApmintReadSuccesses, err = builder.meter.Int64Counter(
		"otelcol_bpf.apmint.read.successes",
		metric.WithDescription("Number of successful reads of APM correlation info [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfDotnetAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.dotnet.attempts",
		metric.WithDescription("Number of attempted dotnet unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfDotnetErrorsBadFp, err = builder.meter.Int64Counter(
		"otelcol_bpf.dotnet.errors.bad_fp",
		metric.WithDescription("Number of failures to read dotnet frame pointer data [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfDotnetErrorsCodeHeader, err = builder.meter.Int64Counter(
		"otelcol_bpf.dotnet.errors.code_header",
		metric.WithDescription("Number of failures to read dotnet CodeHeader [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfDotnetErrorsCodeTooLarge, err = builder.meter.Int64Counter(
		"otelcol_bpf.dotnet.errors.code_too_large",
		metric.WithDescription("Number of failures to unwind dotnet frame due to large code size [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfDotnetErrorsNoProcInfo, err = builder.meter.Int64Counter(
		"otelcol_bpf.dotnet.errors.no_proc_info",
		metric.WithDescription("Number of times we didn't find an entry for this process in the dotnet process info array [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfDotnetFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.dotnet.frames",
		metric.WithDescription("Number of unwound dotnet frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsBadDtvRead, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.bad_dtv_read",
		metric.WithDescription("Number of failures to read TLS variables via the DTV [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsBadTLSAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.bad_tls_addr",
		metric.WithDescription("Number of failures to read from the TLS [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsBadTpBaseAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.bad_tp_base_addr",
		metric.WithDescription("Number of failures to get the TLS base in tls_get_base() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsBpfCurrentComm, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.bpf_current_comm",
		metric.WithDescription("Number of times the bpf helper failed to get the current comm of the task [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsEmptyStack, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.empty_stack",
		metric.WithDescription("Number of times unwind_stop is called without a trace [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsPidEvents, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.pid_events",
		metric.WithDescription("Number of times we failed to update pid_events [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsReportedPids, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.reported_pids",
		metric.WithDescription("Number of times we failed to update reported_pids [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsStackLengthExceeded, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.stack_length_exceeded",
		metric.WithDescription("Number of times MAX_FRAME_UNWINDS has been exceeded in unwind_next_frame() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfErrorsZeroPc, err = builder.meter.Int64Counter(
		"otelcol_bpf.errors.zero_pc",
		metric.WithDescription("Number of failures due to PC == 0 in unwind_next_frame() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfGolabelsAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.golabels.attempts",
		metric.WithDescription("Number of attempts to read Go custom labels [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfGolabelsErrors, err = builder.meter.Int64Counter(
		"otelcol_bpf.golabels.errors",
		metric.WithDescription("Number of failures reading Go custom labels [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.attempts",
		metric.WithDescription("Number of attempted Hotspot frame unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotErrorsInterpreterFp, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.errors.interpreter_fp",
		metric.WithDescription("Number of failures to unwind interpreter due to invalid FP [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotErrorsInvalidCodeblob, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.errors.invalid_codeblob",
		metric.WithDescription("Number of failures to get codeblob data [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotErrorsInvalidRa, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.errors.invalid_ra",
		metric.WithDescription("Number of failures to unwind because return address was not found with heuristic [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotErrorsLrUnwindingMidTrace, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.errors.lr_unwinding_mid_trace",
		metric.WithDescription("Number of times the Hotspot unwind instructions requested LR unwinding mid-trace [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotErrorsNoCodeblob, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.errors.no_codeblob",
		metric.WithDescription("Number of failures to get hotspot codeblob address (no heap or bad segmap) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotErrorsUnsupportedFrameSize, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.errors.unsupported_frame_size",
		metric.WithDescription("Number of times we encountered frame sizes larger than the supported maximum [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfHotspotFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.hotspot.frames",
		metric.WithDescription("Number of unwound Hotspot frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfInterpreterCalls, err = builder.meter.Int64Counter(
		"otelcol_bpf.interpreter.calls",
		metric.WithDescription("Number of calls to interpreter unwinding in dispatch_interpreters() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.attempts",
		metric.WithDescription("Unwind attempts since the previous check [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsBadUnwindInfoIndex, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.bad_unwind_info_index",
		metric.WithDescription("Number of times an unwind_info_array index was invalid [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsChaseIrqStackLink, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.chase_irq_stack_link",
		metric.WithDescription("Number of failures to read the IRQ stack link [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsKernelAddress, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.kernel_address",
		metric.WithDescription("Number of kernel addresses passed to get_text_section() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLookupIterations, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lookup_iterations",
		metric.WithDescription("Number of failures to get stack_unwind_info from big_stack_deltas in get_stack_delta() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLookupRange, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lookup_range",
		metric.WithDescription("Number of failures to get stack_unwind_info from big_stack_deltas in get_stack_delta() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLookupStackDeltaInnerMap, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lookup_stack_delta_inner_map",
		metric.WithDescription("Number of times that a lookup of a inner map for stack deltas failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLookupStackDeltaOuterMap, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lookup_stack_delta_outer_map",
		metric.WithDescription("Number of times that a lookup of the outer map for stack deltas failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLookupTextSection, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lookup_text_section",
		metric.WithDescription("Number of failed range searches within 20 steps in get_stack_delta() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLr0, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lr0",
		metric.WithDescription("Number of times frame unwinding failed because of LR == 0 [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsLrUnwindingMidTrace, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.lr_unwinding_mid_trace",
		metric.WithDescription("Number of times the unwind instructions requested LR unwinding mid-trace [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsPcRead, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.pc_read",
		metric.WithDescription("Number of times failure to read PC from unwound stack (invalid stack delta) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsReadKernelModeRegs, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.read_kernel_mode_regs",
		metric.WithDescription("Number of failures to read the kernel-mode registers [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsStackDeltaInvalid, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.stack_delta_invalid",
		metric.WithDescription("Number of invalid stack deltas in the native unwinder [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeErrorsWrongTextSection, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.errors.wrong_text_section",
		metric.WithDescription("Number of failures to find the text section in get_text_section() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.frames",
		metric.WithDescription("Unwound frames since the previous check [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeSmallPc, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.small_pc",
		metric.WithDescription("Number of times that PC hold a value smaller than 0x1000 [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNativeStackDeltaStop, err = builder.meter.Int64Counter(
		"otelcol_bpf.native.stack_delta_stop",
		metric.WithDescription("Number of stop stack deltas in the native unwinder (success) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNumProcExit, err = builder.meter.Int64Counter(
		"otelcol_bpf.num_proc_exit",
		metric.WithDescription("Number of exit PID events (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNumProcNew, err = builder.meter.Int64Counter(
		"otelcol_bpf.num_proc_new",
		metric.WithDescription("Number of new PID events (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfNumUnknownPc, err = builder.meter.Int64Counter(
		"otelcol_bpf.num_unknown_pc",
		metric.WithDescription("Number of unknown PC events (report_events) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPerlAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.perl.attempts",
		metric.WithDescription("Number of attempted perl unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPerlErrorsReadContextStackEntry, err = builder.meter.Int64Counter(
		"otelcol_bpf.perl.errors.read_context_stack_entry",
		metric.WithDescription("Number of failures to read perl context stack entry [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPerlErrorsReadStackInfo, err = builder.meter.Int64Counter(
		"otelcol_bpf.perl.errors.read_stack_info",
		metric.WithDescription("Number of failures to read perl stack info [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPerlErrorsResolveEgv, err = builder.meter.Int64Counter(
		"otelcol_bpf.perl.errors.resolve_egv",
		metric.WithDescription("Number of failures to resolve perl EGV [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPerlErrorsTLS, err = builder.meter.Int64Counter(
		"otelcol_bpf.perl.errors.tls",
		metric.WithDescription("Number of failures to read perl TLS info [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPerlFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.perl.frames",
		metric.WithDescription("Number of unwound perl frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPhpAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.php.attempts",
		metric.WithDescription("Number of attempted PHP unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPhpErrorsBadCurrentExecuteData, err = builder.meter.Int64Counter(
		"otelcol_bpf.php.errors.bad_current_execute_data",
		metric.WithDescription("Number of failures to read PHP current execute data pointer [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPhpErrorsBadZendExecuteData, err = builder.meter.Int64Counter(
		"otelcol_bpf.php.errors.bad_zend_execute_data",
		metric.WithDescription("Number of failures to read PHP execute data contents [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPhpErrorsBadZendFunction, err = builder.meter.Int64Counter(
		"otelcol_bpf.php.errors.bad_zend_function",
		metric.WithDescription("Number of failures to read PHP zend function contents [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPhpErrorsBadZendOpline, err = builder.meter.Int64Counter(
		"otelcol_bpf.php.errors.bad_zend_opline",
		metric.WithDescription("Number of failures to read PHP zend opline contents [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPhpFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.php.frames",
		metric.WithDescription("Number of unwound PHP frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.attempts",
		metric.WithDescription("Number of attempted python unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsBadAutoTLSKeyAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.bad_auto_tls_key_addr",
		metric.WithDescription("Number of failures to read autoTLSkey [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsBadCframeFrameAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.bad_cframe_frame_addr",
		metric.WithDescription("Number of failures to read _PyCFrame.current_frame in unwind_python() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsBadCodeObjectArgCountAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.bad_code_object_arg_count_addr",
		metric.WithDescription("Number of failures to get code object's argcount in process_python_frame() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsBadPyThreadStateCurrentAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.bad_py_thread_state_current_addr",
		metric.WithDescription("Number of failures to read from pyinfo->pyThreadStateCurrentAddr [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsBadThreadStateFrameAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.bad_thread_state_frame_addr",
		metric.WithDescription("Number of failures to read PyThreadState.frame in unwind_python() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsNoProcInfo, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.no_proc_info",
		metric.WithDescription("Number of times we didn't find an entry for this process in the Python process info array [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsReadThreadStateAddr, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.read_thread_state_addr",
		metric.WithDescription("Number of failures to read the thread state pointer from TLD [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsReadTsdBase, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.read_tsd_base",
		metric.WithDescription("Number of failures to determine the base address for thread-specific data [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonErrorsZeroThreadState, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.errors.zero_thread_state",
		metric.WithDescription("Number of PyThreadState being 0x0 [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.frames",
		metric.WithDescription("Number of unwound python frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfPythonZeroFrameCodeObject, err = builder.meter.Int64Counter(
		"otelcol_bpf.python.zero_frame_code_object",
		metric.WithDescription("Number of NULL code objects found in process_python_frame() [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyAttempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.attempts",
		metric.WithDescription("Number of attempted Ruby unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsInvalidIseq, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.invalid_iseq",
		metric.WithDescription("Number of invalid instruction sequences sequence [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsNoProcInfo, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.no_proc_info",
		metric.WithDescription("Number of times we didn't find an entry for this process in the Ruby process info array [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadCfp, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_cfp",
		metric.WithDescription("Number of failures to read the control frame pointer from the Ruby context [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadCmeMaxEp, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_cme_max_ep",
		metric.WithDescription("Number of failed attempts to read a CME by exceeding max EP checks [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadEp, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_ep",
		metric.WithDescription("Number of failures to read the expression path from the Ruby frame [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadIseqBody, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_iseq_body",
		metric.WithDescription("Number of failures to read the instruction sequence body [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadMethodDef, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_method_def",
		metric.WithDescription("Number of failures to read the Ruby method definition [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadMethodType, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_method_type",
		metric.WithDescription("Number of failures to read the Ruby method type [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadRbasicFlags, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_rbasic_flags",
		metric.WithDescription("Number of failures to read the Ruby rbasic flags [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadStackPtr, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_stack_ptr",
		metric.WithDescription("Number of failures to read the stack pointer from the Ruby context [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadStackSize, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_stack_size",
		metric.WithDescription("Number of failures to read the size of the VM stack from the Ruby context [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyErrorsReadSvar, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.errors.read_svar",
		metric.WithDescription("Number of failures to read the Ruby svar while finding CME [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfRubyFrames, err = builder.meter.Int64Counter(
		"otelcol_bpf.ruby.frames",
		metric.WithDescription("Number of unwound Ruby frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfTailCallsMax, err = builder.meter.Int64Counter(
		"otelcol_bpf.tail_calls_max",
		metric.WithDescription("Number of times stack unwinding was stopped to not hit the limit of tail calls [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfV8Attempts, err = builder.meter.Int64Counter(
		"otelcol_bpf.v8.attempts",
		metric.WithDescription("Number of attempted V8 unwinds [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfV8ErrorsBadCode, err = builder.meter.Int64Counter(
		"otelcol_bpf.v8.errors.bad_code",
		metric.WithDescription("Number of failures to read V8 Code object [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfV8ErrorsBadFp, err = builder.meter.Int64Counter(
		"otelcol_bpf.v8.errors.bad_fp",
		metric.WithDescription("Number of failures to read V8 frame pointer data [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfV8ErrorsBadJsFunc, err = builder.meter.Int64Counter(
		"otelcol_bpf.v8.errors.bad_js_func",
		metric.WithDescription("Number of failures to read V8 Code/JSFunction object [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfV8ErrorsNoProcInfo, err = builder.meter.Int64Counter(
		"otelcol_bpf.v8.errors.no_proc_info",
		metric.WithDescription("Number of times we didn't find an entry for this process in the V8 process info array [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BpfV8Frames, err = builder.meter.Int64Counter(
		"otelcol_bpf.v8.frames",
		metric.WithDescription("Number of unwound V8 frames [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.PerfEventDisableErr, err = builder.meter.Int64Counter(
		"otelcol_perf_event.disable.err",
		metric.WithDescription("Number of times disabling a perf event hook failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.PerfEventEnableErr, err = builder.meter.Int64Counter(
		"otelcol_perf_event.enable.err",
		metric.WithDescription("Number of times enabling a perf event hook failed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProbProfilingInterval, err = builder.meter.Int64Gauge(
		"otelcol_prob.profiling.interval",
		metric.WithDescription("Interval in seconds for which probabilistic profiling will be enabled or disabled. [Development]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ProbProfilingStatus, err = builder.meter.Int64Gauge(
		"otelcol_prob.profiling.status",
		metric.WithDescription("Indicates if probabilistic profiling is enabled or disabled: 1 profiling is enabled, -1 profiling is disabled. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
